[package]
name = "satisfactory"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.127"
hash_tree = { path = "../hash_tree" }
minilp = "0.2.2"
